volumes:
  clsi-cache:
  filestore-public-files:
  filestore-template-files:
  filestore-uploads:
  filestore-user-files:
  mongo-data:
  redis-data:
  sharelatex-data:
  web-data:
  history-v1-buckets:

services:
  chat:
    build:
      context: ..
      dockerfile: services/chat/Dockerfile
    env_file:
      - dev.env

  clsi:
    build:
      context: ..
      dockerfile: services/clsi/Dockerfile
    # target: with-texlive
    env_file:
      - dev.env
    environment:
      - SANDBOXED_COMPILES=true
      - DOWNLOAD_HOST=http://clsi-nginx:8080
    user: root
    volumes:
      - ${PWD}/compiles:/overleaf/services/clsi/compiles
      - ${PWD}/output:/overleaf/services/clsi/output
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
      - clsi-cache:/overleaf/services/clsi/cache

  clsi-nginx:
    image: nginx:1.28
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /run
    volumes:
      - ${PWD}/output:/output:ro
      - ../services/clsi/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

  docstore:
    build:
      context: ..
      dockerfile: services/docstore/Dockerfile
    env_file:
      - dev.env

  document-updater:
    build:
      context: ..
      dockerfile: services/document-updater/Dockerfile
    env_file:
      - dev.env

  filestore:
    build:
      context: ..
      dockerfile: services/filestore/Dockerfile
    env_file:
      - dev.env
    #    environment:
    #      - ENABLE_CONVERSIONS=true
    volumes:
      - filestore-public-files:/overleaf/services/filestore/public_files
      - filestore-template-files:/overleaf/services/filestore/template_files
      - filestore-uploads:/overleaf/services/filestore/uploads
      - history-v1-buckets:/buckets

  history-v1:
    build:
      context: ..
      dockerfile: services/history-v1/Dockerfile
    env_file:
      - dev.env
    environment:
      OVERLEAF_EDITOR_ANALYTICS_BUCKET: "/buckets/analytics"
      OVERLEAF_EDITOR_BLOBS_BUCKET: "/buckets/blobs"
      OVERLEAF_EDITOR_CHUNKS_BUCKET: "/buckets/chunks"
      OVERLEAF_EDITOR_PROJECT_BLOBS_BUCKET: "/buckets/project_blobs"
      OVERLEAF_EDITOR_ZIPS_BUCKET: "/buckets/zips"
      PERSISTOR_BACKEND: fs
    volumes:
      - history-v1-buckets:/buckets

  linked-url-proxy:
    build:
      context: ..
      dockerfile: services/linked-url-proxy/Dockerfile
    env_file:
      - dev.env

  mongo:
    image: mongo:8
    command: --replSet overleaf
    ports:
      - "127.0.0.1:27017:27017" # for debugging
    volumes:
      - mongo-data:/data/db
      - ../bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      # Required when using the automatic database setup for initializing the
      # replica set. This override is not needed when running the setup after
      # starting up mongo.
      - mongo:127.0.0.1

  notifications:
    build:
      context: ..
      dockerfile: services/notifications/Dockerfile
    env_file:
      - dev.env

  project-history:
    build:
      context: ..
      dockerfile: services/project-history/Dockerfile
    env_file:
      - dev.env

  real-time:
    build:
      context: ..
      dockerfile: services/real-time/Dockerfile
    env_file:
      - dev.env

  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379" # for debugging
    volumes:
      - redis-data:/data

  web:
    build:
      context: ..
      dockerfile: services/web/Dockerfile
      target: dev
    env_file:
      - dev.env
    environment:
      - APP_NAME=Overleaf Community Edition
      - ENABLED_LINKED_FILE_TYPES=project_file,project_output_file,url,mendeley,zotero
      - EMAIL_CONFIRMATION_DISABLED=true
      - NODE_ENV=development
      - OVERLEAF_ALLOW_PUBLIC_ACCESS=true
    command: ["node", "app.mjs"]
    volumes:
      - sharelatex-data:/var/lib/overleaf
      - web-data:/overleaf/services/web/data
      - ./data/certs/:/var/lib/overleaf/certs/
    depends_on:
      - mongo
      - redis
      - chat
      - clsi
      - docstore
      - document-updater
      - filestore
      - history-v1
      - linked-url-proxy
      - notifications
      - project-history
      - real-time

  webpack:
    build:
      context: ..
      dockerfile: services/web/Dockerfile
      target: webpack
    command:
      ["npx", "webpack", "serve", "--config", "webpack.config.dev-env.js"]
    ports:
      - "127.0.0.1:80:3808"
    volumes:
      - ./webpack.config.dev-env.js:/overleaf/services/web/webpack.config.dev-env.js

  git-bridge:
    image: quay.io/sharelatex/git-bridge:latest
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      GIT_BRIDGE_API_BASE_URL: "http://web:3000/api/v0"
      GIT_BRIDGE_OAUTH2_SERVER: "http://web:3000"
      GIT_BRIDGE_POSTBACK_BASE_URL: "http://git-bridge:8000"
      GIT_BRIDGE_ROOT_DIR: "/data/git-bridge"
      LOG_LEVEL: "DEBUG"
    volumes:
      - ./data/git-bridge:/data/git-bridge
  
# services: 
  # Overleaf Dev Containers
  # ...
  
  # Add those for your development
  # API debug
  hoppscotch-frontend:
    image: hoppscotch/hoppscotch-frontend:latest
    ports:
      - "3000:3000"

  hoppscotch-proxy:
    image: hoppscotch/proxyscotch:latest
    environment:
      - PORT=9159
    ports:
      - "9159:9159"


  # Redis-insight
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - ./data/redis-insight:/data

  # mongo-express
  # basicAuth credentials are "admin:pass"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
  
  # For ldap testing
  # https://github.com/rroemhild/docker-test-openldap
  ldap:
    restart: always
    image: ghcr.io/rroemhild/docker-test-openldap:v2.5.0